global using System.Net;
global using Newtonsoft.Json;
global using Weather.NET.Enums;
global using Weather.NET.Exceptions;
global using Weather.NET.Extensions;
global using Weather.NET.Models.GeoCodingModel;
global using Weather.NET.Models.WeatherModel;
global using Weather.NET.Models.OneCallModel;
global using Weather.NET.Models.PollutionModel;