name: CD

on:
  push:
    branches: release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore code/Weather.NET.csproj
    - name: Build
      run: dotnet build code/Weather.NET.csproj --no-restore
    - name: Test
      run: dotnet test code/Weather.NET.csproj --no-build --verbosity normal
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: code/Weather.NET.csproj
        PACKAGE_NAME: Weather.NET
        NUGET_KEY: ${{ secrets.NUGET_KEY }}